### ISSUE TITLE
Enable json_batch for cfe-16 input

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/cfe_16#1]
**Description**

"enable json_batch for cfe-16 input"

**Use case or motivation behind the feature request**

N/A

**Related issues**

**Additional context**

Restored issue

**Comment by 51-code** [comment]
Needs more information about what kind of an input it didn't work with. Might be that the issue is irrelevant to json batch. I have tested sending batched input similar to this in JMeter:
```
{"sourcetype": "abc", "event": "xyz"}
{"sourcetype": "abc", "event": "xyz"}
{"sourcetype": "abc", "event": "xyz"}
{"sourcetype": "abc", "event": "xyz"}
{"sourcetype": "abc", "event": "xyz"}
```

and it seems to work just fine. Handling batched input is implemented in `EventManager`'s `convertData` function.

**Comment by 51-code** [comment]
Supports multiple JSON inputs but not in a JSON array. See example above.
